#!/bin/bash
set -e

function usage {
    echo "Usage:";
    echo "./formula help:                 Show this help";
    echo "./formula install <env>:        Install a new helm release";
    echo "./formula upgrade <env>:        Install a new helm release";
    echo "./formula status <env>:         Install a new helm release";
    echo "./formula delete <env>:         Install a new helm release";
}

if [ "$1" == "help" ];
then
    usage
    exit;
fi

if [ "$#" -ne 2 ];
then
    usage;
    exit 1;
fi

if [ "$1" == "install" ] || [ "$1" == "upgrade" ];
then
    secrets=$(kubectl get secret libero-reviewer--$2 -o json);
    continuumJwtSecret=$(echo $secrets | jq -r .data.continuumJwtSecret | base64 -d);
    authenticationJwtSecret=$(echo $secrets | jq -r .data.authenticationJwtSecret | base64 -d);
    installFlag=""

    # if [ "$1" == "install" ]; then
    #     echo "installing $2 release";
    #     installFlag=" --install"
    # else
    #     echo "upgrade $2 release";
    # fi

    helm upgrade --install libero-reviewer--$2 ./helm/libero-reviewer -f environments/$2.yaml \
--wait \
--timeout 120 \
--set \
continuumAdaptor.continuumJwtSecret="$continuumJwtSecret",\
continuumAdaptor.authenticationJwtSecret="$authenticationJwtSecret";

    exit;
fi

if [ "$1" == "status" ];
then
    helm status libero-reviewer--$2;
    exit;
fi

if [ "$1" == "delete" ];
then
    helm del --purge libero-reviewer--$2;
    exit;
fi

usage;
exit 1;