apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-submission
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {
      "port": 3000,
      "databases": {
        "submission": {
          "type": "pg",
          "database": "{{ .Values.postgresql.postgresqlDatabase }}",
          "username": "{{ .Values.postgresql.postgresqlUsername }}",
          "password": "{{ .Values.postgresql.postgresqlPassword }}",
          "host": "{{ include "libero-reviewer.fullname" . }}-postgresql",
          "port": "{{ .Values.postgresql.servicePort }}"
        },
        "survey": {
          "type": "pg",
          "database": "{{ .Values.postgresql.postgresqlDatabase }}",
          "username": "{{ .Values.postgresql.postgresqlUsername }}",
          "password": "{{ .Values.postgresql.postgresqlPassword }}",
          "host": "{{ include "libero-reviewer.fullname" . }}-postgresql",
          "port": "{{ .Values.postgresql.servicePort }}"
        }
      }
    }