apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-submission
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {
      "port": 3000,
      "max_ql_complexity": 100,
      "max_ql_depth": 5,
      "knex": {
          "client": "pg",
          "connection": {
              "host": "{{ include "libero-reviewer.fullname" . }}-postgresql",
              "database": "{{ .Values.postgresql.postgresqlDatabase }}",
              "user": "{{ .Values.postgresql.postgresqlUsername }}",
              "password": "{{ .Values.postgresql.postgresqlPassword }}",
              "port": 5432,
          }
      },
      "authentication_jwt_secret": "{{ .Values.continuumAdaptor.authenticationJwtSecret }}",
      "user_adapter_url": "http://{{ include "libero-reviewer.fullname" . }}-continuum-adaptor/current-user",
      "science_beam": {
        "api_url": "{{ .Values.submission.scienceBeam.apiUrl }}",
        "timeout": {{ .Values.submission.scienceBeam.timeout }}
      },
      "s3": {
        "accessKeyId": "{{ .Values.submission.aws.accessKeyId }}",
        "secretAccessKey": "{{ .Values.submission.aws.secretAccessKey }}",
        "s3ForcePathStyle": true,
        "fileBucket": "{{ .Values.submission.aws.s3Bucket }}",
        "awsEndPoint": false
      }
    }