apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-submission
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {
      "port": 3000,
      "knex": {
          "client": "pg",
          "connection": {
              "host": "{{ include "libero-reviewer.fullname" . }}-postgresql",
              "database": "{{ .Values.postgresql.postgresqlDatabase }}",
              "user": "{{ .Values.postgresql.postgresqlUsername }}",
              "password": "{{ .Values.postgresql.postgresqlPassword }}",
              "port": 5432,
              "max_ql_complexity": 100,
              "max_ql_depth": 5
          }
      },
      "authentication_jwt_secret": "{{ .Values.continuumAdaptor.authenticationJwtSecret }}",
      "user_adapter_url": "http://{{ include "libero-reviewer.fullname" . }}-continuum-adaptor"
    }