apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-client
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.images.client.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: CLIENT_PORT
              value: "9000"
            - name: CLIENT_API_URL
              value: "https://{{ include "libero-reviewer.fullname" . }}.elifesciences.org"
            - name: CLIENT_API_PROXY_URL
              value: "http://{{ include "libero-reviewer.fullname" . }}-submission"
            - name: CLIENT_AUTH_PROXY_URL
              value: "http://{{ include "libero-reviewer.fullname" . }}-continuum-auth"
            - name: CONTINUUM_LOGIN_URL
              value: "{{ .Values.continuumLogin.url }}"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP